const input = {id:'input',kind:'input',title:'确认资料范围',description:'选择本任务允许使用的文件和文件夹；可以预览内容后再确认。',outputs:['输入范围快照'],tools:[]};
const run = (id,title,description,tools,outputs,optional=false)=>({id,kind:'execute',title,description,tools,outputs,optional});
const review = {id:'review',kind:'review',title:'复核与归档',description:'查看各阶段实际产物，记录复核意见并归档。疑点和 AI 解释不自动成为审计结论。',tools:[],outputs:['阶段成果汇总','复核意见','任务记录包']};
export const workflowDefinitions = [
 {id:'data',title:'表格与资料整理',group:'资料准备',description:'检查结构、整理字段，形成可追溯的数据副本。',inputHint:'Excel、CSV、PDF、资料文件夹',stages:[input,run('inspect','检查数据结构','查看工作表、原始行和列信息。',['inspect','file_inventory'],['结构报告','输入清单']),run('process','整理资料','选择本次需要的整理动作，设置字段后执行。',['merge_files','select_column','fill_column','merge_column','add_column','dropsummary','text_match','duplicates','pdf_text','mcp_headers_process','mcp_select_column','mcp_fill_column','mcp_merge_column','mcp_add_column','mcp_dropsummary','mcp_text_match','mcp_data_field_check','mcp_file_classification','mcp_insert_column','mcp_multi_collect_file','mcp_multi_collect_folder','mcp_pickup_value'],['整理文件','处理统计']),review]},
 {id:'ledger',title:'科目、账簿与凭证',group:'账务核查',description:'核对借贷平衡，按 JET 规则识别疑点分录。',inputHint:'序时账、总账、科目余额表',stages:[input,run('inspect','检查账簿结构','确认凭证、金额和科目字段。',['inspect','mcp_jet_test_inspect','mcp_tool_preview'],['结构检查报告']),run('normalize','科目整理（可选）','仅在字段需要整理时执行，输出可供后续选用。',['subject_clean','mcp_tool_execute','mcp_asist_split','mcp_auxiliary_selection','mcp_subject_allocation','mcp_subject_clean_after'],['科目清理结果'],true),run('test','凭证与 JET 测试','选择借贷核对或 JET 测试，并明确规则和参数。',['voucher_check','jet_test','mcp_jet_test_execute','mcp_ledger_check','mcp_voucher_check'],['疑点分录','规则命中结果']),review]},
 {id:'monthly',title:'月间分析与测算',group:'账务核查',description:'确认科目和期间口径，分析月度变化与原因线索。',inputHint:'本期、上期序时账',stages:[input,run('preview','预览期间数据','读取表头、样本和期间字段。',['inspect','mcp_monthly_preview'],['数据源概览']),run('structure','识别科目结构（可选）','复杂科目编码可先识别层级，简单数据可直接确认分析字段。',['mcp_monthly_detect_structure'],['编码层级报告'],true),run('analysis','确认字段并分析','确认日期、科目和金额映射后生成月度汇总。',['monthly_analysis','mcp_monthly_execute','mcp_gross_margin_analysis'],['月度汇总表','变动明细']),run('explain','原因分析（可选）','选择分析结果和原始数据，对确认的科目生成 AI 原因草稿。',['mcp_monthly_ai_analysis'],['AI 原因分析草稿'],true),review]},
 {id:'sampling',title:'抽凭与抽样',group:'账务核查',description:'检查总体，按截止测试配置生成样本并留存依据。',inputHint:'交易明细、凭证、截止抽样配置表',note:'当前接口提供截止测试抽样；其他抽样方法尚未注册，不能在此执行。',stages:[input,run('population','检查总体','查看数据源结构，复核配置表中的总体和期间范围。',['inspect'],['总体数据预览']),run('sample','截止测试抽样','选择配置表，确认配置中的日期范围、样本条件和输出目录。',['mcp_cutoff_sampling'],['样本清单','抽样工具报告']),review]},
 {id:'bank',title:'银行业务',group:'专项核查',description:'汇集银行流水，双向核对账务并生成函证。',inputHint:'银行流水、序时账、函证配置表',stages:[input,run('merge','汇集流水（可选）','按文件确认表头、银行、账户和交易字段。',['mcp_bankflowmerge'],['合并流水'],true),run('reconcile','双向核对','分别指定序时账和银行流水，核对金额、日期与对手方。',['mcp_bank_flow'],['核对报告','未匹配流水']),run('letter','生成函证（可选）','根据函证配置表选择电子或纸质格式。',['mcp_bank_digit2','mcp_bank_paper1','mcp_bank_paper2'],['银行函证文件'],true),review]},
 {id:'workpaper',title:'底稿与明细表',group:'成果编制',description:'检查源数据和模板，保存映射、校验并生成底稿。',inputHint:'源数据、模板文件夹、工作目录',note:'明细表生成依赖本机 64 位 Excel。配置需按工具要求保存完整后再校验。',stages:[input,run('source','检查源数据','识别公司、科目和源字段。',['mcp_detailed_table_inspect'],['数据源检查报告']),run('template','检查模板','读取模板工作表与批注字段。',['mcp_detailed_table_inspect_template'],['模板字段清单']),run('configure','保存映射配置','分别保存路径、字段、科目、模板分配等配置，可在本阶段多次保存后确认。',['mcp_detailed_table_save_config'],['配置保存记录']),run('validate','校验配置','验证配置完整性与源数据一致性，查看报告后确认。',['mcp_detailed_table_validate'],['校验报告']),run('generate','生成底稿','按已确认配置生成文件；覆盖选项默认关闭。',['mcp_detailed_table_generate','mcp_xlsx_writer'],['底稿文件','生成报告']),review]},
 {id:'disclosure',title:'披露、附注与链接',group:'成果编制',description:'提取披露口径与表格，检查引用和附注批注。',inputHint:'披露配置、附注、Excel 底稿',stages:[input,run('scope','提取披露口径（可选）','从配置表指定的资料提取披露范围。',['mcp_extract_disclosure_scope'],['披露范围'],true),run('tables','提取披露表（可选）','按配置提取披露表并核对范围。',['mcp_extract_disclosure_tables'],['披露表'],true),run('links','检查链接与批注','选择链接提取或所需维护动作，执行前核对影响文件。',['link_extract','mcp_link_extractor','mcp_insert_footnote_comments','mcp_link_ref_replace','mcp_link_replace_range','mcp_link_replace_text','mcp_link_replace_workbook'],['链接或批注处理结果']),review]},
 {id:'external',title:'关联方与外部查询',group:'专项核查',description:'查询主体信息，整理关联线索及来源证据。',inputHint:'企业名称、工商资料、关联方名单',note:'外部查询需要对应服务授权和网络连接，查询时间及原始响应随任务保留。',stages:[{...input,optional:true},run('query','查询主体信息','选择工商查询、公告下载或已有企查查报告处理。',['mcp_cicpa_query','mcp_qcc_processor','mcp_announcement','mcp_ipo_bj','mcp_ipo_sh','mcp_ipo_sz'],['主体查询结果','来源记录']),run('related','识别关联方（可选）','指定被审计单位和工商资料目录，识别需要人工确认的关系。',['mcp_related_party'],['疑似关联方','匹配依据'],true),review]},
 {id:'aux',title:'信息提取与辅助处理',group:'资料准备',description:'提取 PDF 与图片内容，解析地址和身份信息。',inputHint:'PDF、图片、文本、处理配置表',stages:[{...input,optional:true},run('extract','选择处理任务','按资料类型选择提取、解析或辅助核对能力。',['pdf_text','mcp_info_extract','mcp_info_extract_multi','mcp_address_split','mcp_id_card','mcp_paper_verify','mcp_photo_rename','mcp_ai_formula_filler','mcp_currency'],['结构化结果','处理报告']),review]}
];
