import {_electron as electron} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {workflowDefinitions} from '../../src/workflows/definitions.mjs';
const out=path.resolve('artifacts/repair-20261008');const env={...process.env,AUDIT_DATA_DIR:path.join(out,'catalog-state-'+Date.now()),AUDIT_NODE:path.resolve('build/runtime/node.exe'),AUDIT_PYTHON:path.resolve('build/python/python.exe')};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({executablePath:path.resolve('node_modules/electron/dist/electron.exe'),args:['.'],env,timeout:30000});const observed=new Set(),errors=[];let stages=0;
try{const page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'任务中心',exact:true}).waitFor();await page.getByRole('button',{name:'体验示例项目'}).click();await page.locator('.project-picker option').filter({hasText:'合成示例'}).waitFor({state:'attached'});
 for(const definition of workflowDefinitions){await page.locator('.task-card-new').filter({hasText:definition.title}).click();await page.locator('h1').filter({hasText:'确认资料范围'}).waitFor();for(let i=0;i<definition.stages.length;i++){const stage=definition.stages[i];await page.locator('.workflow-steps>button').nth(i).click();await page.locator('h1').filter({hasText:stage.title}).waitFor();stages++;if(stage.kind==='execute'){const select=page.getByLabel('处理操作');for(const id of stage.tools){await select.selectOption(id);await page.locator('.input-contract').waitFor();assert.ok(await select.inputValue()===id);observed.add(id);}}
 }await page.getByRole('button',{name:'任务中心',exact:true}).click();console.log('Checked '+definition.id);}
 await page.locator('.task-card-new').filter({hasText:'抽凭与抽样'}).click();await page.locator('.workflow-steps>button').filter({hasText:'截止测试抽样'}).click();await page.getByRole('button',{name:'准备配置模板',exact:true}).click();await page.locator('.template-contract').getByText(/模板版本/).waitFor();const boot=await page.evaluate(()=>window.audit.invoke('bootstrap'));assert.ok(fs.existsSync(path.join(boot.projects[0].root,'input','截止测试配置表.xlsx')));
 assert.equal(observed.size,79);assert.equal(stages,43);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'catalog-ui-results.json'),JSON.stringify({stages,uniqueTools:observed.size,tools:[...observed],templateCopy:true,errors},null,2));console.log(JSON.stringify({stages,uniqueTools:observed.size,templateCopy:true,errors}));
}finally{await app.close();}
