import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {agentServer} from '../fixtures/agent-server.mjs';import {createBackend} from '../../src/host/service.mjs';import {createModelTools} from '../../src/host/model-tools.mjs';import {Attachments} from '../../src/conversations/attachments.mjs';
const root=path.resolve('artifacts/test-results');
async function wait(backend,id){for(let i=0;i<300;i++){const r=await backend.action('session.get',{id});if(!r.streaming)return r;await new Promise(r=>setTimeout(r,100));}throw Error('Agent did not finish');}
for(const [source,failOnce] of [['project',false],['attachments',false],['project',true]])test('real automatic file workflow: '+source+(failOnce?' with failure recovery':''),async()=>{
 const dir=fs.mkdtempSync(path.join(root,'agent-')),input=path.join(dir,'原件');fs.mkdirSync(input);const file=path.join(input,'客户余额.csv'),original='客户,余额,备注\n甲公司,6000,已核对\n乙公司,4000,待核对\n';fs.writeFileSync(file,original);const server=await agentServer({source,operation:'select_column',failOnce}),backend=await createBackend({dataRoot:path.join(dir,'state')});
 try{const p=source==='project'?await backend.action('project.create',{name:'测试资料',root:input}):null,s=await backend.action('session.create',{projectId:p?.id});await backend.action('settings.save',{baseUrl:server.baseUrl,model:'tool-fixture'});const items=source==='attachments'?(await backend.action('attachments.import',{sessionId:s.id,paths:[file]})).attachments:[];await backend.action('chat.send',{sessionId:s.id,text:'读取资料并提取客户、余额两列，输出结果',attachments:items.map(a=>a.id)});const result=await wait(backend,s.id);assert.equal(result.events.at(-1).type,'assistant',JSON.stringify(result.events));assert.match(result.events.at(-1).text,/实际处理 2 行/);assert.equal(result.events.at(-1).toolCount,failOnce?6:5);assert.equal(result.events.at(-1).usage.total_tokens,failOnce?175:150);assert.equal(result.calls.length,failOnce?6:5);assert.equal(result.calls.filter(c=>c.status==='failed').length,failOnce?1:0);assert.equal(result.tasks.length,failOnce?2:1);assert.equal(result.tasks.at(-1).status,'succeeded');assert.ok(fs.existsSync(await backend.action('result.path',{id:result.tasks.at(-1).id,name:result.tasks.at(-1).result.outputs[0].name})));assert.equal(fs.readFileSync(file,'utf8'),original);assert.ok(server.requests[0].tools.length>=5);assert.equal(server.requests[1].messages.find(m=>m.tool_calls)?.reasoning_content,'需要以真实工具结果为依据。');assert.equal((await backend.action('bootstrap')).projects.length,source==='project'?1:0);const foreign=await backend.action('session.create');const tools=createModelTools({store:backend.store,scheduler:{},attachments:new Attachments(backend.store),session:foreign,settings:{},catalog:[],signal:new AbortController().signal,onPhase:()=>{}});await assert.rejects(tools.execute('get_task_result',{taskId:result.tasks.at(-1).id}),/不属于/);await assert.rejects(tools.execute('shell',{command:'anything'}),/未获授权/);if(p){const scoped=createModelTools({store:backend.store,scheduler:{},attachments:new Attachments(backend.store),session:s,settings:{},catalog:[],signal:new AbortController().signal,onPhase:()=>{}});await assert.rejects(scoped.execute('preview_local_file',{source:'project',file:'../state/metadata.sqlite'}),/授权目录/);}
 }finally{backend.close();await server.close();}
});
test('stopping generation cancels the active real local task',async()=>{
 const dir=fs.mkdtempSync(path.join(root,'agent-cancel-')),input=path.join(dir,'原件');fs.mkdirSync(input);fs.writeFileSync(path.join(input,'大表.csv'),'客户,余额\n'+'甲公司,6000\n'.repeat(100000));const server=await agentServer({operation:'inspect'}),backend=await createBackend({dataRoot:path.join(dir,'state')});
 try{const p=await backend.action('project.create',{name:'停止测试',root:input}),s=await backend.action('session.create',{projectId:p.id});await backend.action('settings.save',{baseUrl:server.baseUrl,model:'tool-fixture'});await backend.action('chat.send',{sessionId:s.id,text:'处理大表'});let active=false;for(let i=0;i<200;i++){const r=await backend.action('session.get',{id:s.id});if(r.tasks.some(t=>t.status==='running')){active=true;break;}await new Promise(r=>setTimeout(r,25));}assert.ok(active,'task must actually start');await backend.action('chat.cancel',{sessionId:s.id});const stopped=await wait(backend,s.id);assert.equal(stopped.streaming,false);assert.match(stopped.events.at(-1).text,/已停止/);assert.ok(stopped.calls.some(c=>c.status==='cancelled'));for(let i=0;i<50;i++){const r=await backend.action('session.get',{id:s.id});if(r.tasks.every(t=>!['running','queued','cancelling'].includes(t.status)))break;await new Promise(r=>setTimeout(r,50));}const final=await backend.action('session.get',{id:s.id});assert.ok(final.tasks.every(t=>['cancelled','succeeded'].includes(t.status)));assert.ok(!final.events.some(e=>e.type==='assistant'));
 }finally{backend.close();await server.close();}
});
