import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {Store} from '../../src/conversations/store.mjs';import {Scheduler} from '../../src/task-scheduler/scheduler.mjs';
const base=path.resolve('artifacts/test-results');fs.mkdirSync(base,{recursive:true});process.env.AUDIT_PYTHON=path.resolve('build/python/python.exe');
const wait=async(store,id,states)=>{for(let i=0;i<400;i++){const t=store.get('tasks',id);if(states.includes(t.status))return t;await new Promise(r=>setTimeout(r,50));}throw Error('Task timed out');};
test('active cancellation, queued cancellation, retry uses same task id and one result directory',async()=>{
 const root=fs.mkdtempSync(path.join(base,'scheduler-'));const p=path.join(root,'project');fs.mkdirSync(p);fs.writeFileSync(path.join(p,'input.csv'),'a,b\n1,2\n3,4\n');const store=new Store(path.join(root,'state'));const session=store.create('sessions',{title:'test'});const scheduler=new Scheduler(store);const project={id:'p',root:p};
 try{const first=scheduler.queue(session,project,'inspect',['input.csv'],'auto',{}, {memoryMiB:512,threads:1});const queued=scheduler.queue(session,project,'inspect',['input.csv'],'auto',{}, {memoryMiB:512,threads:1});scheduler.cancel(queued.id);scheduler.cancel(first.id);assert.equal((await wait(store,first.id,['cancelled','failed','succeeded'])).status,'cancelled');assert.equal(store.get('tasks',queued.id).status,'cancelled');scheduler.retry(first.id);const done=await wait(store,first.id,['succeeded','failed']);assert.equal(done.status,'succeeded',done.error);assert.equal(done.result.rowCount,2);assert.equal(store.all('tasks').length,2);assert.equal(fs.readdirSync(path.join(p,'outputs')).filter(x=>!x.startsWith('.')).length,1);}finally{scheduler.stop();store.close();fs.rmSync(root,{recursive:true,force:true});}
});
test('restart marks orphan running tasks as interrupted',()=>{const root=fs.mkdtempSync(path.join(base,'recovery-'));const store=new Store(root);try{const s=store.create('sessions',{title:'test'});const t=store.create('tasks',{sessionId:s.id,status:'running'});const scheduler=new Scheduler(store);assert.equal(store.get('tasks',t.id).status,'interrupted');assert.equal(store.events(s.id).at(-1).taskId,t.id);scheduler.stop();}finally{store.close();fs.rmSync(root,{recursive:true,force:true});}});
