import React, {useEffect,useState} from 'react';
import {ArrowRight, BookOpenCheck, Clock3, Files, FolderOpen, Plus, Search, Settings2} from 'lucide-react';
import {api} from './api';
import {Dialog,Workflow,statusLabel} from './Workflow';
import type {Boot,Project,Session,Tool} from './types';
import {TASK_DEFINITIONS,TASK_GROUPS,TASK_ICONS,type TaskDefinition} from './taskDefinitions';

export function RedesignedApp({boot,initialProject,allTools,onRefresh,onSelectProject,onCreateProject,onDemo,onError,onNotice}:{boot:Boot;initialProject?:Project;allTools:Tool[];onRefresh:()=>Promise<Boot>;onSelectProject:(p:Project)=>void;onCreateProject:(name:string,root:string)=>Promise<void>;onDemo:()=>Promise<void>;onError:(e:unknown)=>void;onNotice:(s:string)=>void}){
 const [nav,setNav]=useState('tasks'),[group,setGroup]=useState('全部任务'),[search,setSearch]=useState(''),[opened,setOpened]=useState<{id:string;definition:TaskDefinition;project:Project}|null>(null),[create,setCreate]=useState(false),[name,setName]=useState(''),[root,setRoot]=useState(''),[busy,setBusy]=useState(false);
 const project=initialProject;
 const action=async(fn:()=>Promise<any>)=>{setBusy(true);try{await fn();}catch(e){onError(e);}finally{setBusy(false);}};
 const newTask=(definition:TaskDefinition)=>action(async()=>{if(!project){setCreate(true);onNotice('请先建立项目，再开始任务');return;}const r=await api('workflow.create',{projectId:project.id,definitionId:definition.id});await onRefresh();setOpened({id:r.session.id,definition,project});});
 const resume=(session:Session)=>action(async()=>{const r=await api('workflow.get',{id:session.id});const definition=TASK_DEFINITIONS.find(x=>x.id===r.workflow.definitionId)!;const p=boot.projects.find(x=>x.id===session.projectId);if(!p)throw Error('项目不存在');onSelectProject(p);setOpened({id:session.id,definition,project:p});});
 const sessions=boot.sessions.filter(s=>s.projectId===project?.id&&(s.workflow||s.title?.startsWith('审计任务 · '))).slice().sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''));
 const visible=TASK_DEFINITIONS.filter(d=>(group==='全部任务'||d.group===group)&&`${d.title} ${d.description} ${d.stages.flatMap(s=>s.tools).map(id=>allTools.find(t=>t.id===id)?.name).join(' ')}`.toLowerCase().includes(search.toLowerCase()));
 const rows=(items:Session[])=><div className="record-list">{items.map(s=><button key={s.id} className="record-row" onClick={()=>resume(s)} disabled={busy}><Clock3 size={18}/><span><strong>{s.title.replace('审计任务 · ','')}</strong><small>{s.updatedAt?new Date(s.updatedAt).toLocaleString('zh-CN'):s.id.slice(0,8)} · {s.workflow?Object.values(s.workflow.stages).filter((x:any)=>x.status==='confirmed'||x.status==='skipped').length+' 个阶段已确认':'历史执行记录'}</small></span><span className="record-status">{statusLabel(s.workflow?.status)}</span><ArrowRight size={16}/></button>)}</div>;
 return <>{opened?<Workflow key={opened.id} {...opened} boot={boot} allTools={allTools} onError={onError} onNotice={onNotice} onBack={()=>{setOpened(null);setNav('tasks');onRefresh().catch(onError);}}/>:<div className="redesign-shell"><aside className="redesign-nav"><div className="redesign-logo"><BookOpenCheck size={24}/><strong>审计工作台</strong></div><span className="nav-caption">项目工作区</span>{[{id:'tasks',name:'任务中心',Icon:Files},{id:'history',name:'处理记录',Icon:Clock3},{id:'settings',name:'运行设置',Icon:Settings2}].map(({id,name,Icon})=><button key={id} className={'redesign-nav-item '+(nav===id?'active':'')} onClick={()=>setNav(id)}><Icon size={18}/>{name}</button>)}<div className="nav-project"><FolderOpen size={18}/><span>{project?.name||'尚未选择项目'}</span></div><div className="redesign-nav-version">版本 {boot.version}<br/>{boot.build?'构建 '+new Date(boot.build).toLocaleString('zh-CN'):''}</div></aside><main className="redesign-main"><header className="redesign-header"><div><span className="eyebrow">{project?.name||'本地审计工作区'}</span><h1>{nav==='tasks'?'任务中心':nav==='history'?'处理记录':'运行设置'}</h1><p>{nav==='tasks'?'选择业务任务，确认资料、处理规则与阶段成果。':nav==='history'?'继续处理任务，或打开已归档的复核记录。':'配置实际执行所需的服务与本机环境。'}</p></div><div className="project-actions"><label>当前项目<select className="project-picker" value={project?.id||''} onChange={e=>{const p=boot.projects.find(x=>x.id===e.target.value);if(p)onSelectProject(p);}}><option value="" disabled>请选择项目</option>{boot.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button onClick={()=>setCreate(true)}><Plus size={17}/>新建项目</button></div></header>
 {!project&&<section className="project-empty-banner"><div><strong>建立项目，组织资料和成果</strong><p>选定资料目录后，所有执行与复核记录会关联到该项目。</p></div><button onClick={()=>action(onDemo)} disabled={busy}>体验示例项目</button><button className="primary" onClick={()=>setCreate(true)}>创建项目</button></section>}
 {nav==='tasks'?<>{sessions.length>0&&<section className="recent-panel"><div className="card-heading"><h2>最近的工作</h2><button onClick={()=>setNav('history')}>全部记录</button></div>{rows(sessions.slice(0,3))}</section>}<div className="task-center-toolbar"><div className="task-group-tabs" aria-label="任务分类">{TASK_GROUPS.map(g=><button key={g} aria-pressed={g===group} className={g===group?'selected':''} onClick={()=>setGroup(g)}>{g}</button>)}</div><label className="task-search"><Search size={17}/><input aria-label="搜索任务" placeholder="搜索任务或处理操作" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><section className="task-card-grid">{visible.map(d=>{const Icon=TASK_ICONS[d.id as keyof typeof TASK_ICONS];return <button key={d.id} className="task-card-new" onClick={()=>newTask(d)} disabled={busy}><div className="task-card-top"><Icon size={22}/><span>{d.group}</span></div><h2>{d.title}</h2><p>{d.description}</p><div className="task-card-bottom"><span>{d.stages.length} 个阶段</span><ArrowRight size={18}/></div></button>;})}</section>{visible.length===0&&<p className="empty-state">未找到匹配任务，试试其他关键词。</p>}</>:nav==='history'?<section><div className="card-heading"><h2>项目任务（{sessions.length}）</h2><span>已归档 {sessions.filter(s=>s.workflow?.status==='archived').length}</span></div>{sessions.length?rows(sessions):<p className="empty-state">还没有处理记录。从任务中心开始一项任务。</p>}</section>:<Settings boot={boot} onRefresh={onRefresh} onError={onError} onNotice={onNotice}/>}</main></div>}
 {create&&<Dialog title="建立审计项目" onClose={()=>!busy&&setCreate(false)}><div className="project-form"><label>项目名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="例如：华东制造 2026 年审"/></label><label>资料目录<div className="path-control"><input value={root} onChange={e=>setRoot(e.target.value)} placeholder="选择项目资料所在目录"/><button onClick={()=>action(async()=>{const dir=await api('choose.directory');if(dir)setRoot(dir);})}>选择目录</button></div></label><p className="helper">使用项目工作副本。各工具是否会修改输入，会在执行前说明。</p><button className="primary" disabled={busy||!name.trim()||!root.trim()} onClick={()=>action(async()=>{await onCreateProject(name.trim(),root.trim());setCreate(false);setName('');setRoot('');})}>创建项目</button></div></Dialog>}</>;
}

export function Settings({boot,onRefresh,onError,onNotice}:{boot:Boot;onRefresh:()=>Promise<Boot>;onError:(e:unknown)=>void;onNotice:(s:string)=>void}){
 const [config,setConfig]=useState({...boot.settings}),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[runtime,setRuntime]=useState<any>(),[message,setMessage]=useState('');
 useEffect(()=>{api('runtime.status').then(setRuntime).catch(onError);},[]);
 const action=async(fn:()=>Promise<any>)=>{setBusy(true);setMessage('');try{await fn();}catch(e:any){setMessage(e.message);onError(e);}finally{setBusy(false);}};
 return <div className="settings-layout"><section className="workspace-card"><h2>模型服务</h2><p>本地确定性处理不需要模型。AI 操作需要对应服务与授权。</p><div className="settings-fields"><label>API 地址<input value={config.baseUrl} onChange={e=>setConfig({...config,baseUrl:e.target.value})}/></label><label>文本模型<input value={config.model} onChange={e=>setConfig({...config,model:e.target.value})}/></label><label>视觉模型<input value={config.visionModel||''} onChange={e=>setConfig({...config,visionModel:e.target.value})} placeholder="图片识别任务使用"/></label><label>API 密钥<input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={boot.settings.hasKey?'已保存，留空保留现有密钥':'输入密钥，保存时使用系统加密'}/></label><label>默认执行方式<select value={config.defaultMode||'auto'} onChange={e=>setConfig({...config,defaultMode:e.target.value})}><option value="auto">自动选择</option><option value="local-light">本地轻量</option><option value="local-batch">本地批量</option></select></label></div><p className="helper">执行方式用于内置处理器的资源策略；工具箱操作使用其自身执行引擎。</p><div className="settings-actions"><button className="primary" disabled={busy} onClick={()=>action(async()=>{await api('settings.save',config);if(key.trim()){await api('secret.save',{key});setKey('');}await onRefresh();onNotice('服务与运行设置已保存');})}>保存设置</button><button disabled={busy} onClick={()=>action(async()=>{const r=await api('connection.test',{settings:config,key:key||undefined});setMessage('连接测试完成：'+JSON.stringify(r));})}>测试连接</button><button disabled={busy} onClick={()=>action(async()=>{const r=await api('models.list',{settings:config,key:key||undefined});setMessage('可用模型：'+JSON.stringify(r));})}>查看可用模型</button></div>{message&&<p role="status" className="settings-feedback">{message}</p>}</section><section className="workspace-card"><h2>运行环境</h2>{runtime?<div className="runtime-list"><div><strong>审计工具箱</strong><span>{runtime.mcpAvailable?'已找到本机程序':'未找到，请检查安装路径'}</span><small>{runtime.mcpPath}</small></div><div><strong>Microsoft Excel</strong><span>{runtime.excel64?'已找到 64 位 Excel':runtime.excel?'检测到 Excel，非 64 位':'未在标准安装位置找到'}</span><small>明细表生成需要 64 位 Excel；其他任务按各工具要求执行。</small></div><div><strong>工作流规范</strong><span>已加载 {runtime.skills.length} 项规范</span><small>业务规范在任务阶段内查看；维护类规范不作为审计任务入口。</small></div><div><strong>当前构建</strong><span>{boot.version}</span><small>{boot.build&&new Date(boot.build).toLocaleString('zh-CN')}</small></div></div>:<p>正在检查本机环境…</p>}</section></div>;
}
