import React, {useEffect, useRef, useState} from 'react';
import {ArrowLeft, Check, FolderOpen, Play, RefreshCw, X, FileText, ChevronRight, Plus} from 'lucide-react';
import {api} from './api';
import type {Boot, FileSystemEntry, Project, TaskCard, Tool, ToolField} from './types';
import type {TaskDefinition} from './taskDefinitions';

const active=(status?:string)=>['queued','running','cancelling'].includes(status||'');
export const statusLabel=(s?:string)=>({succeeded:'执行成功',failed:'执行失败',cancelled:'已停止',interrupted:'已中断',queued:'等待执行',running:'执行中',confirmed:'已确认',skipped:'已跳过',archived:'已归档',pending:'待处理',awaiting_confirmation:'待确认成果',awaiting_input:'需要确认参数',in_progress:'进行中'}[s||'']||'待处理');
const initial=(tool?:Tool)=>Object.fromEntries((tool?.fields||[]).filter(f=>f.default!==undefined).map(f=>[f.key,f.default]));
const safeDraft=(draft:any,tool?:Tool)=>({...draft,parameters:Object.fromEntries(Object.entries(draft.parameters||{}).filter(([key])=>!tool?.fields.some(f=>f.key===key&&f.kind==='secret')))});

export function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const el=ref.current;el?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const nodes=Array.from(el?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')||[]);const first=nodes[0],last=nodes.at(-1);if(!first){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===el)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};el?.addEventListener('keydown',key);return()=>{el?.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className="workspace-overlay"><div className="workspace-dialog" role="dialog" aria-modal="true" aria-label={title} ref={ref} tabIndex={-1}><header><h2>{title}</h2><button aria-label="关闭" onClick={onClose}><X size={18}/></button></header>{children}</div></div>;
}

export function FileChooser({project,kind='path',extensions,onChoose,onClose}:{project:Project;kind?:string;extensions?:string[]|null;onChoose:(path:string)=>void;onClose:()=>void}){
 const [folder,setFolder]=useState(''),[entries,setEntries]=useState<FileSystemEntry[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);api('files.list',{projectId:project.id,path:folder}).then(x=>{if(live){setEntries(x);setError('');}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[folder]);
 return <Dialog title={kind==='directory'?'选择项目内目录':'选择项目资料'} onClose={onClose}><div className="picker-path"><button disabled={!folder||loading} onClick={()=>setFolder(folder.split(/[\\/]/).slice(0,-1).join('/'))}>上一级</button><span>{folder||'项目根目录'}</span>{['directory','path'].includes(kind)&&<button className="primary" onClick={()=>onChoose(folder||'.')}>使用此目录</button>}</div>{error&&<p role="alert">{error}</p>}<div className="picker-list">{loading?<p>正在读取资料…</p>:entries.map(file=>{const supported=file.directory||!extensions?.length||extensions.some(x=>file.name.toLowerCase().endsWith(x));return <div key={file.path}><span>{file.directory?<FolderOpen size={18}/>:<FileText size={18}/>}</span><span>{file.name}<small>{file.directory?'文件夹':supported?file.path:'格式不适用于当前功能'}</small></span>{file.directory?<><button onClick={()=>setFolder(file.path)}>打开</button>{kind!=='file'&&<button onClick={()=>onChoose(file.path)}>选用目录</button>}</>:kind!=='directory'&&<button disabled={!supported} onClick={()=>onChoose(file.path)}>选用文件</button>}</div>;})}</div><p className="helper">范围：{project.root}。{extensions?.length?'当前可选后缀：'+extensions.join(' / '):'按本任务需要选择文件或目录。'}</p></Dialog>;
}

export function DataPreview({data}:{data:any}){
 const columns=(data?.columns||[]).map((x:any)=>typeof x==='object'?x.name||x.column||JSON.stringify(x):String(x));const rows=data?.preview||data?.sample_rows||[];
 if(!columns.length||!Array.isArray(rows)||!rows.length)return data?.sheets||data?.workbooks?<pre className="structured-result">{JSON.stringify(data.sheets||data.workbooks,null,2)}</pre>:null;
 return <div className="data-preview"><table><thead><tr>{columns.map((c:string,i:number)=><th key={i}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,50).map((row:any,i:number)=><tr key={i}>{columns.map((c:string,j:number)=><td key={j}>{String(Array.isArray(row)?row[j]??'':row[c]??'')}</td>)}</tr>)}</tbody></table><p className="helper">预览最多 50 行；完整数据以成果文件为准。</p></div>;
}
function JsonEditor({field,value,onChange,columns}:{field:ToolField;value:any;onChange:(x:any)=>void;columns:string[]}){
 let parsed:any;try{parsed=JSON.parse(value||'{}');}catch{}
 const mapping=['column_mapping','field_mapping','mapping'].includes(field.key);
 const [raw,setRaw]=useState(false);
 const defaults=field.key==='mapping'?['公司','凭证日期','凭证编号','科目编码','借方金额','贷方金额','摘要','制单人','审核人']:field.key==='column_mapping'?['date','subject_code','subject_name','debit','credit','company','desc','voucher']:['营业收入','营业成本','数量','日期','会计主体'];
 if(mapping&&!raw&&parsed&&typeof parsed==='object'&&!Array.isArray(parsed))return <div className="mapping-editor"><div className="mapping-title"><span>标准字段 → 数据列</span><button type="button" onClick={()=>setRaw(true)}>编辑 JSON</button></div>{[...new Set([...defaults,...Object.keys(parsed)])].map(key=><label key={key}><span>{({date:'日期',subject_code:'科目代码',subject_name:'科目名称',debit:'借方金额',credit:'贷方金额',company:'公司名称',desc:'摘要',voucher:'凭证号'} as any)[key]||key}</span><input list="source-columns" value={parsed[key]||''} onChange={e=>onChange(JSON.stringify({...parsed,[key]:e.target.value}))} placeholder="选择或输入源列名"/></label>)}</div>;
 if(field.key==='subjects'&&!raw&&(!value||Array.isArray(parsed))){const rows=Array.isArray(parsed)?parsed:[];return <div className="subject-editor">{rows.map((row:any,i:number)=><div key={i}><input aria-label={`科目代码 ${i+1}`} value={row.code||''} placeholder="科目代码" onChange={e=>onChange(JSON.stringify(rows.map((r:any,j:number)=>j===i?{...r,code:e.target.value}:r)))}/><select aria-label={`借贷方向 ${i+1}`} value={row.direction||'贷'} onChange={e=>onChange(JSON.stringify(rows.map((r:any,j:number)=>j===i?{...r,direction:e.target.value}:r)))}><option>借</option><option>贷</option></select><button onClick={()=>onChange(JSON.stringify(rows.filter((_:any,j:number)=>j!==i)))}>移除</button></div>)}<button onClick={()=>onChange(JSON.stringify([...rows,{code:'',direction:'贷'}]))}>添加科目</button></div>;}
 return <div><textarea aria-label={field.label} rows={4} value={value||''} onChange={e=>onChange(e.target.value)} placeholder="填写 JSON 配置"/>{mapping&&<button type="button" onClick={()=>setRaw(false)}>使用字段映射表</button>}</div>;
}

export function ParameterForm({tool,params,onChange,onPick,columns,jetRules,disabled,onPreview}:{tool:Tool;params:any;onChange:(k:string,v:any)=>void;onPick:(field:ToolField)=>void;columns:string[];jetRules:any[];disabled:boolean;onPreview:(file:string)=>void}){
 const [advanced,setAdvanced]=useState(false);
 const render=(field:ToolField)=>{
  const value=params[field.key],set=(v:any)=>onChange(field.key,v);
  if(['file','directory','path'].includes(field.kind||''))return <div className="role-input"><span>{Array.isArray(value)?value.join('\n'):value||'尚未指定'}</span><button disabled={disabled} type="button" onClick={()=>onPick(field)}>{field.type==='array'?'添加文件':'选择'+(field.kind==='directory'?'目录':'资料')}</button>{value&&<button disabled={disabled} onClick={()=>set(undefined)}>清除</button>}{typeof value==='string'&&field.kind!=='directory'&&<button disabled={disabled} onClick={()=>onPreview(value)}>预览字段</button>}</div>;
  if(field.kind==='json')return <JsonEditor field={field} value={value} onChange={set} columns={columns}/>;
  if(field.type==='boolean')return <select aria-label={field.label} value={value===undefined?'':String(value)} onChange={e=>set(e.target.value===''?undefined:e.target.value==='true')}><option value="">使用工具默认值</option><option value="true">是</option><option value="false">否</option></select>;
  if(field.enum)return <select aria-label={field.label} value={value||''} onChange={e=>set(e.target.value)}><option value="">请选择</option>{field.enum.map(x=><option key={x}>{x}</option>)}</select>;
  if(field.type==='array')return <textarea aria-label={field.label} rows={3} value={(value||[]).join('\n')} onChange={e=>set(e.target.value.split('\n'))} placeholder="每行一项，空行保留相应文件的空字段"/>;
  if(field.key==='rules'&&tool.id==='jet_test')return <div className="rule-list">{jetRules.map((r:any,i:number)=>{const name=r.name||r.rule||String(r);const selected=String(value||'').split(',');return <label key={i}><input type="checkbox" checked={selected.includes(name)} onChange={e=>set(e.target.checked?[...selected.filter(Boolean),name].join(','):selected.filter(x=>x!==name).join(','))}/><span>{name}</span></label>;})}</div>;
  return <input aria-label={field.label} type={field.kind==='secret'?'password':['number','integer'].includes(field.type||'')?'number':/^(start_date|end_date)$/.test(field.key)?'date':'text'} step={field.type==='integer'?1:'any'} list={field.kind==='column'||/列/.test(field.label)?'source-columns':undefined} value={value??''} onChange={e=>set(['number','integer'].includes(field.type||'')?(e.target.value===''?undefined:Number(e.target.value)):e.target.value)} placeholder={field.default!==undefined?String(field.default):field.required?'必填':'可选，留空使用工具默认值'}/>;
 };
 const primary=tool.fields.filter(f=>f.required||['file','directory','path','json'].includes(f.kind||'')||['columns','headerRow','subjects','rules','confirmed'].includes(f.key));
 const rest=tool.fields.filter(f=>!primary.includes(f));
 const fieldView=(f:ToolField)=><div className={`parameter-field ${['json','path','file','directory'].includes(f.kind||'')||f.type==='array'?'wide':''}`} key={f.key}><label>{f.label}{f.required&&!f.allowBlank?' *':''}</label>{render(f)}{f.help&&f.help!==f.label&&<details className="field-help"><summary>填写说明</summary><small>{f.help}</small></details>}</div>;
 if(tool.id==='mcp_bankflowmerge')return <fieldset disabled={disabled} className="parameter-form"><h3>按文件配置账户与表头</h3>{fieldView(tool.fields.find(f=>f.key==='file_paths')!)}{(params.file_paths||[]).map((file:string,i:number)=><section className="bank-file-config" key={i}><div className="card-heading"><strong>{file}</strong><button onClick={()=>onPreview(file)}>预览表头</button></div><div className="typed-parameters">{tool.fields.filter(f=>f.type==='array'&&f.key!=='file_paths').map(f=><label key={f.key}>{f.label.replace('列表','')}<input value={params[f.key]?.[i]??''} onChange={e=>{const list=(params.file_paths||[]).map((_:any,j:number)=>params[f.key]?.[j]||'');list[i]=e.target.value;onChange(f.key,list);}} placeholder={f.key==='header_start_cols'?'A':f.key==='header_start_rows'?'1':'按该文件填写；无需时留空'}/></label>)}</div></section>)}</fieldset>;
 if(tool.id==='mcp_bank_flow')return <fieldset disabled={disabled} className="parameter-form"><datalist id="source-columns">{columns.map(c=><option key={c} value={c}/>)}</datalist><div className="bank-pair">{[{prefix:'gl_',title:'序时账字段'},{prefix:'bank_',title:'银行流水字段'}].map(group=><section key={group.prefix}><h3>{group.title}</h3><div className="typed-parameters">{tool.fields.filter(f=>f.key.startsWith(group.prefix)).map(fieldView)}</div></section>)}</div></fieldset>;
 return <fieldset disabled={disabled} className="parameter-form"><datalist id="source-columns">{columns.map(c=><option key={c} value={c}/>)}</datalist><div className="typed-parameters">{primary.map(f=><div className={`parameter-field ${['json','path','file','directory'].includes(f.kind||'')||f.type==='array'?'wide':''}`} key={f.key}><label>{f.label}{f.required&&!f.allowBlank?' *':''}</label>{render(f)}{f.help&&f.help!==f.label&&<details className="field-help"><summary>填写说明</summary><small>{f.help}</small></details>}</div>)}</div>{rest.length>0&&<><button className="advanced-toggle" type="button" onClick={()=>setAdvanced(!advanced)}>{advanced?'收起':'展开'}可选参数（{rest.length}）</button>{advanced&&<div className="typed-parameters">{rest.map(f=><div className="parameter-field" key={f.key}><label>{f.label}</label>{render(f)}{f.help&&f.help!==f.label&&<details className="field-help"><summary>填写说明</summary><small>{f.help}</small></details>}</div>)}</div>}</>}</fieldset>;
}

export function Workflow({id,definition,project,boot,allTools,onBack,onError,onNotice}:{id:string;definition:TaskDefinition;project:Project;boot:Boot;allTools:Tool[];onBack:()=>void;onError:(e:unknown)=>void;onNotice:(s:string)=>void}){
 const [record,setRecord]=useState<any>(),[stageId,setStageId]=useState('input'),[draft,setDraft]=useState<any>({parameters:{},files:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[picker,setPicker]=useState<ToolField|null>(null),[review,setReview]=useState(''),[reason,setReason]=useState(''),[preview,setPreview]=useState<any>(),[previewFile,setPreviewFile]=useState(''),[guidesOpen,setGuidesOpen]=useState(false),[ack,setAck]=useState(false),[showInputs,setShowInputs]=useState(true);
 const stage=definition.stages.find(s=>s.id===stageId)||definition.stages[0],w=record?.workflow;
 const available=stage.tools.map(id=>allTools.find(t=>t.id===id)).filter(Boolean) as Tool[];
 const tool=available.find(t=>t.id===draft.toolId)||available[0];
 const task=record?.tasks.find((t:TaskCard)=>t.id===w?.stages[stageId]?.taskId) as TaskCard|undefined;
 useEffect(()=>{if(task?.status==='succeeded')setShowInputs(false);},[task?.id,task?.status]);
 const executing=record?.tasks.some((t:TaskCard)=>active(t.status));
 const archived=w?.status==='archived';
 const columns=[...new Set([...(preview?.columns||[]),...(record?.tasks||[]).filter((t:TaskCard)=>t.status==='succeeded').flatMap((t:TaskCard)=>t.result?.columns||[])].map((x:any)=>typeof x==='string'?x:x.name||x.column).filter(Boolean))] as string[];
 const load=async()=>{const data=await api('workflow.get',{id});setRecord(data);return data;};
 const chooseStage=(data:any,next:string)=>{const st=definition.stages.find(s=>s.id===next)||definition.stages[0];const defaultTool=allTools.find(t=>t.id===st.tools[0]);setStageId(st.id);setShowInputs(true);setDraft(data.workflow.drafts[st.id]||{toolId:defaultTool?.id,parameters:initial(defaultTool),files:[...data.workflow.files]});setAck(false);setPreview(undefined);setPreviewFile('');setError('');};
 useEffect(()=>{let live=true;api('workflow.get',{id}).then(data=>{if(live){setRecord(data);setReview(data.workflow.review||'');chooseStage(data,data.workflow.activeStage);}}).catch(onError);return()=>{live=false;};},[id]);
 useEffect(()=>{if(!executing)return;let live=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const data=await api('workflow.get',{id});if(live)setRecord(data);}catch(e:any){if(live)setError(e.message);}if(live)timer=setTimeout(poll,1000);};timer=setTimeout(poll,700);return()=>{live=false;clearTimeout(timer);};},[executing,id]);
 const persist=async()=>{if(!record||archived||executing)return record;const data=await api('workflow.save',{id,activeStage:stageId,stageId:stage.kind==='execute'?stageId:undefined,draft:stage.kind==='execute'?safeDraft(draft,tool):undefined,review});setRecord(data);return data;};
 useEffect(()=>{if(!record||archived||busy||executing)return;const timer=setTimeout(()=>{persist().catch((e:any)=>setError(e.message));},650);return()=>clearTimeout(timer);},[draft,review,stageId,busy,executing]);
 const action=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);onError(e);}finally{setBusy(false);}};
 const switchStage=(next:string)=>action(async()=>{const data=await persist();await api('workflow.save',{id,activeStage:next}).catch(e=>{if(!archived)throw e;});chooseStage(data,next);});
 const run=()=>action(async()=>{await persist();const roles=tool.fields.filter(f=>['file','directory','path'].includes(f.kind||'')).flatMap(f=>Array.isArray(draft.parameters[f.key])?draft.parameters[f.key]:[draft.parameters[f.key]]).filter(Boolean);await api('task.run',{sessionId:id,stageId,tool:tool.id,files:[...new Set([...(draft.files||[]),...roles])],parameters:draft.parameters,mode:boot.settings.defaultMode||'auto',acknowledgeMutation:ack});await load();onNotice('任务已开始，执行记录会持续保存');});
 const confirm=(skip=false)=>action(async()=>{await persist();const data=await api('workflow.confirm',{id,stageId,skip,reason,review});setRecord(data);chooseStage(data,data.workflow.activeStage);setReason('');onNotice(data.workflow.status==='archived'?'复核意见与任务记录包已归档':'阶段已确认');});
 const pick=(value:string)=>action(async()=>{if(picker?.key==='$scope'){const data=await api('workflow.save',{id,files:[...new Set([...w.files,value])]});setRecord(data);setDraft((d:any)=>({...d,files:data.workflow.files}));}else if(picker?.key==='$files'){setDraft((d:any)=>({...d,files:[...new Set([...(d.files||[]),value])]}));}else if(picker){const key=picker.key;setDraft((d:any)=>{const parameters={...d.parameters,[key]:picker.type==='array'?[...new Set([...(d.parameters[key]||[]),value])]:value};if(tool?.id==='mcp_bankflowmerge'&&key==='file_paths')for(const f of tool.fields.filter(f=>f.type==='array'&&f.key!=='file_paths'))parameters[f.key]=parameters.file_paths.map((_:any,i:number)=>d.parameters[f.key]?.[i]??(f.key==='header_start_cols'?'A':f.key==='header_start_rows'?'1':''));return {...d,parameters};});}setPicker(null);});
 const inspect=(file:string)=>action(async()=>{const data=await api('files.preview',{projectId:project.id,file,parameters:{headerRow:draft.parameters.headerRow||1}});setPreview(data);setPreviewFile(file);});
 if(!record)return <main className="workspace-loading">正在恢复任务记录…</main>;
 const index=definition.stages.findIndex(s=>s.id===stageId),blocked=definition.stages.slice(0,index).find(s=>!['confirmed','skipped'].includes(w.stages[s.id]?.status));
 const pendingTask=task&&active(task.status);
 const removeFile=(file:string)=>stage.kind==='input'?action(async()=>{setRecord(await api('workflow.save',{id,files:w.files.filter((x:string)=>x!==file)}));}):setDraft((d:any)=>({...d,files:d.files.filter((x:string)=>x!==file)}));
 const files=stage.kind==='input'?w.files:draft.files||[];
 return <div className="audit-workspace"><header className="workspace-header"><button onClick={()=>action(async()=>{await persist();onBack();})}><ArrowLeft size={17}/>返回工作台</button><div><strong>{definition.title}</strong><span>{project.name} · {statusLabel(w.status)}</span></div><span className="record-id">任务 {id.slice(0,8)} · 自动保存</span></header><div className="workspace-body"><nav className="workflow-steps" aria-label="任务阶段"><p>{definition.group}</p>{definition.stages.map((s,i)=>{const st=w.stages[s.id]?.status;return <button key={s.id} className={s.id===stageId?'current':''} onClick={()=>switchStage(s.id)} disabled={busy}><span>{st==='confirmed'?<Check size={16}/>:i+1}</span><div><strong>{s.title.replace('（可选）','')}</strong><small>{st==='skipped'?'已跳过':st==='confirmed'?'已确认':st==='awaiting_confirmation'?'待确认成果':s.optional?'可选阶段':'必要阶段'}</small></div></button>;})}<div className="workflow-guide"><button onClick={()=>setGuidesOpen(!guidesOpen)}>查看处理规范 {record.guides.length>0&&`(${record.guides.length})`}</button>{guidesOpen&&<>{record.guides.length?record.guides.map((g:any)=><details key={g.id}><summary>{g.id}</summary><pre>{g.text}</pre></details>):<p>按阶段确认输入、执行结果与复核意见。结果不自动成为审计结论。</p>}</>}</div></nav><main className="workspace-main"><div className="stage-heading"><div><span>阶段 {index+1} / {definition.stages.length}</span><h1>{stage.title}</h1><p>{stage.description}</p></div><span className="stage-state">{statusLabel(w.stages[stageId]?.status)}</span></div>{w.legacyImported&&<p className="dependency-note">已恢复旧记录中的资料、参数与执行结果。旧版未保存人工确认状态，请重新核对并确认各阶段。</p>}{definition.note&&<p className="dependency-note">{definition.note}</p>}{error&&<div className="form-error" role="alert" tabIndex={-1}>{error}</div>}{blocked&&!archived&&<div className="stage-blocked">执行前请先确认“{blocked.title}”。你可以先查看或准备本阶段内容。<button onClick={()=>switchStage(blocked.id)}>前往该阶段</button></div>}
 {stage.kind==='input'&&<section className="workspace-card"><h2>本任务的资料范围</h2><p>{definition.inputHint}。{stage.optional?'直接查询可以不选文件。':'后续阶段可分别指定每份资料的用途。'}</p><div className="scope-files">{files.map((file:string)=><div key={file}><FileText size={18}/><span>{file}</span><button disabled={archived||busy||executing} onClick={()=>inspect(file)}>预览</button><button disabled={archived||busy||executing} onClick={()=>removeFile(file)}>移除</button></div>)}</div><button disabled={archived||busy||executing} onClick={()=>setPicker({key:'$scope',label:'任务资料',kind:'path'})}><Plus size={16}/>添加文件或目录</button><p className="helper">确认范围会保存资料清单；不同功能的格式要求会在执行前检查。修改范围后，需要重新确认后续阶段。</p></section>}
 {stage.kind==='execute'&&tool&&<><details className="workspace-card input-card" open={showInputs} onToggle={e=>setShowInputs(e.currentTarget.open)}><summary>输入与处理规则{task?.status==='succeeded'?' · 展开检查本次参数':''}</summary><div className="card-heading"><h2>处理内容</h2><span>{available.length} 项操作</span></div><select className="operation-select" aria-label="处理操作" disabled={archived||executing||busy} value={tool.id} onChange={e=>{const next=available.find(t=>t.id===e.target.value)!;setDraft({toolId:next.id,parameters:initial(next),files:files});setAck(false);}}>{available.map(t=><option key={t.id} value={t.id}>{t.name}{t.engine==='builtin'?' · 本地处理':' · 工具箱'}</option>)}</select><p>{tool.description}</p><div className="input-contract"><strong>输入要求</strong><span>{tool.contract?.format}</span>{tool.contract?.dependency&&<span>{tool.contract.dependency}</span>}</div>{Boolean(tool.contract?.templates?.length)&&<div className="template-contract"><div><strong>配套配置模板</strong><p>{tool.contract?.templates?.join('、')}</p></div><button disabled={archived||executing||busy} onClick={()=>action(async()=>{const result=await api('templates.copy',{projectId:project.id,tool:tool.id});setDraft((d:any)=>({...d,template:result.files,parameters:{...d.parameters,...(tool.fields.some(f=>f.key==='config_file')?{config_file:result.files[0].path}:{})}}));onNotice('配置模板已放入项目 input 目录；已有文件保留。请先填写配置再执行。');})}>准备配置模板</button>{draft.template?.map((f:any)=><small key={f.path}>{f.path} · 模板版本 {f.templateHash.slice(0,12)} {f.existed?'（保留已有文件）':''}</small>)}</div>}{tool.contract?.inputMode==='files'&&<><h3>处理文件</h3><div className="scope-files">{files.map((file:string)=><div key={file}><FileText size={16}/><span>{file}</span><button onClick={()=>inspect(file)} disabled={busy}>预览</button><button onClick={()=>removeFile(file)} disabled={archived||executing}>移除</button></div>)}</div><button disabled={archived||executing} onClick={()=>setPicker({key:'$files',label:'处理文件',kind:'path'})}>添加处理文件</button></>}
 <ParameterForm tool={tool} params={draft.parameters} onChange={(key,value)=>setDraft((d:any)=>({...d,parameters:{...d.parameters,[key]:value}}))} onPick={setPicker} columns={columns} jetRules={boot.jetRules} onPreview={inspect} disabled={archived||executing||busy}/>
 {tool.contract?.inputMode==='roles'&&<div className="preview-actions">{tool.fields.filter(f=>['file','path'].includes(f.kind||'')&&typeof draft.parameters[f.key]==='string'&&draft.parameters[f.key]).map(f=><button disabled={busy} key={f.key} onClick={()=>inspect(draft.parameters[f.key])}>预览{f.label}</button>)}</div>}
 {tool.contract?.mutates&&!archived&&<label className="mutation-confirm"><input type="checkbox" checked={ack} disabled={executing} onChange={e=>setAck(e.target.checked)}/><span>此工具可能修改资料或已有输出。我已选用工作副本，并确认本次处理范围。</span></label>}
 <div className="run-actions"><button className="primary" onClick={run} disabled={!!blocked||busy||executing||archived||!!tool.contract?.mutates&&!ack}><Play size={16}/>{pendingTask?'正在执行':'执行本阶段'}</button>{pendingTask&&<button onClick={()=>action(async()=>{await api('task.cancel',{id:task.id});await load();})}>停止任务</button>}<span>{executing?'后台正在处理，可以离开页面后继续查看。':'参数与文件会随本次执行记录保存。'}</span></div></details></>}
 {preview&&<section className="workspace-card"><div className="card-heading"><h2>资料预览</h2><button onClick={()=>setPreview(undefined)}>关闭预览</button></div><p>{previewFile}</p><DataPreview data={preview}/>{!preview.columns?.length&&<pre className="structured-result">{preview.text||JSON.stringify(preview,null,2)}</pre>}</section>}
 {stage.kind==='execute'&&<section className="workspace-card stage-results" aria-label="阶段成果"><div className="card-heading"><h2>阶段成果</h2><span className={`result-status ${task?.status||''}`}>{task?statusLabel(task.status):'等待执行'}</span></div>{task?<><p>{task.phase}</p>{task.error&&<div className="form-error" role="alert">{task.error}</div>}<div className="result-metrics">{task.result?.rowCount!==undefined&&<span>结果行数 <strong>{task.result.rowCount}</strong></span>}<span>文件 <strong>{task.result?.outputs?.length||0}</strong></span><span>警告 <strong>{task.result?.warnings?.length||0}</strong></span></div><div className="output-list-real">{task.result?.outputs?.map((f,i)=><div key={i}><FileText size={18}/><span>{f.name}<small>{f.path}</small></span><button onClick={()=>action(()=>api('result.open',{id:task.id,name:f.name,path:f.path}))}>打开成果</button><button onClick={()=>inspect(f.path||`${(task.result as any).outputDir}/${f.name}`)}>预览</button></div>)}</div><DataPreview data={task.result}/>{task.result?.warnings?.map((x,i)=><p className="dependency-note" key={i}>{x}</p>)}{Boolean(task.result?.content?.length)&&<details open={!task.result?.outputs?.length}><summary>工具返回详情</summary><pre className="structured-result">{(task.result?.content||[]).map((x:any)=>x.text||JSON.stringify(x)).join('\n')}</pre></details>}{['failed','interrupted','cancelled'].includes(task.status)&&<button disabled={busy||executing||archived} onClick={()=>action(async()=>{await persist();await api('task.retry',{id:task.id});await load();})}>按原参数重试</button>}</>:<p>执行后展示实际结果、错误原因与可打开的成果文件。</p>}</section>}
 {stage.kind==='review'&&<section className="workspace-card"><h2>复核与归档</h2><p>逐项检查执行结果，填写复核意见后生成记录包。</p><div className="review-stage-list">{definition.stages.filter(s=>s.kind!=='review').map(s=><div key={s.id}><strong>{s.title}</strong><span>{statusLabel(w.stages[s.id]?.status)}</span><small>{w.stages[s.id]?.reason}</small><button onClick={()=>switchStage(s.id)}>查看</button></div>)}</div><label className="review-label">复核意见 *<textarea rows={5} value={review} disabled={archived} onChange={e=>setReview(e.target.value)} placeholder="记录已核对的成果、发现的问题、处理结论及保留事项"/></label>{w.archive&&<div className="archive-files"><p>已归档：{new Date(w.archive.at).toLocaleString('zh-CN')}</p>{w.archive.files.map((name:string)=><button key={name} onClick={()=>action(()=>api('workflow.archiveOpen',{id,name}))}>{name}</button>)}</div>}</section>}
 {!archived&&<section className="stage-confirmation"><div><h2>{stage.kind==='review'?'完成复核':'确认本阶段'}</h2><p>{stage.kind==='execute'?'检查上方结果后确认，后续阶段才可执行。':'确认内容将记录到当前任务。'}</p></div><button className="primary" disabled={!!blocked||busy||executing||(stage.kind==='execute'&&task?.status!=='succeeded')} onClick={()=>confirm()}>{stage.kind==='review'?'生成记录包并归档':'确认并继续'}<ChevronRight size={16}/></button>{stage.optional&&<div className="skip-stage"><input aria-label="跳过原因" value={reason} onChange={e=>setReason(e.target.value)} placeholder="若无需此阶段，请填写跳过原因"/><button disabled={!!blocked||busy||executing||!reason.trim()} onClick={()=>confirm(true)}>记录原因并跳过</button></div>}</section>}
 {record.tasks.length>0&&<details className="previous-runs"><summary>本任务全部执行记录（{record.tasks.length}）</summary>{record.tasks.map((t:TaskCard)=><div key={t.id}><span>{allTools.find(x=>x.id===t.tool)?.name||t.tool} · {statusLabel(t.status)}</span><small>{t.createdAt}</small>{t.error&&<p>{t.error}</p>}{t.result?.outputs?.map((f,i)=><button key={i} onClick={()=>action(()=>api('result.open',{id:t.id,name:f.name,path:f.path}))}>{f.name}</button>)}</div>)}</details>}
 </main></div>{picker&&<FileChooser project={project} kind={picker.kind||'path'} extensions={picker.key==='$scope'?null:picker.key==='config_file'?['.xlsx','.xlsm']:tool?.contract?.extensions} onChoose={pick} onClose={()=>setPicker(null)}/>}</div>;
}
